### ISSUE TITLE
timeline of project?

### ISSUE THREAD

**Issue by poppy-nicolette** [qsslab/oatrackeR#1]
Hello everyone, 
we discussed timeline objectives yesterday. Perhaps we should map out something so that everyone can plan? I tend to be overly ambitious, so perhaps a more balanced view is needed:
March - 
April - 
June - 
July - 
August -

**Comment by pmongeon** [comment]
I would divide the next steps into the following three chunks and target dates:

- Create and document a MySQL database that will store the data. **March 5**

- Check the OA status of a DOI. **March 12-19**
- Check availability in the institutional repository. **March 12-19**
- Check which version of the paper is available in the institutional repository. **March 12-19**
- Collect the Sherpa Romeo information that we need. **End of April**

- Create functions and packages - **Mid July**
- Polish, document, and release  - **End of August**

**Comment by poppy-nicolette** [comment]
added to main
